version: '3.9'

services:
  auth-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile-auth-server
    ports:
      - 8080:8080
    networks:
      - auth-net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_db
    hostname: authdbhost
    expose:
      - "3306"
    networks:
    - auth-net
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 5s
      retries: 10

networks:
  auth-net: